### ISSUE TITLE
Feature request: test mode to check blocking/captcha flow

### ISSUE THREAD

**Issue by kenyee** [PerimeterX/perimeterx-java-sdk#110]
Would be nice if there were a test mode where the SDK would fire off a blocking result or captcha result so we can do UI integration tests to test these two flows in the app to make sure they're handled properly from an Espresso UI test.

Currently, you have to use the console, blacklist your IP, etc. to force this to happen.

**Comment by noamlevipx** [comment]
Pls contact our service. It can be quite easy to make you special rule to block you based on special header, user-agent or anything you like
